services:
  - type: web
    name: clmis
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/ping
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: APP_SECRET
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_URL
        sync: false
      - key: MAIL_HOST
        value: smtp-relay.brevo.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: MAIL_FROM_NAME
        value: CLMIS System
